<datalist id="cityList">
    <option>Addalaichenai</option>
    <option>Adippala</option>
    <option>Agalawatta</option>
    <option>Agaliya</option>
    <option>Agarapathana</option>
    <option>Agbopura</option>
    <option>Ahangama</option>
    <option>Ahungalla</option>
    <option>Akaragama</option>
    <option>Akarawita</option>
    <option>Akarella</option>
    <option>Akkaraipattu</option>
    <option>Akkarasiyaya</option>
    <option>Akmeemana</option>
    <option>Akuramboda</option>
    <option>Akurana</option>
    <option>Akuressa</option>
    <option>Alahengama</option>
    <option>Alahitiyawa</option>
    <option>Alapaladeniya</option>
    <option>Alawala</option>
    <option>Alawatugoda</option>
    <option>Alawatura</option>
    <option>Alawatuwala</option>
    <option>Alawwa</option>
    <option>Algama</option>
    <option>Alubomulla</option>
    <option>Aludeniya</option>
    <option>Aluketiyawa</option>
    <option>Alutgama</option>
    <option>Aluthwala</option>
    <option>Alutnuwara</option>
    <option>Aluttaramma</option>
    <option>Alutwewa</option>
    <option>Alwatta</option>
    <option>Ambadandegama</option>
    <option>Ambagahapelessa</option>
    <option>Ambagahawatta</option>
    <option>Ambagamuwa Udabulathgama</option>
    <option>Ambagasdowa</option>
    <option>Ambagaspitiya</option>
    <option>Ambakandawila</option>
    <option>Ambakote</option>
    <option>Ambalakanda</option>
    <option>Ambalangoda</option>
    <option>Ambalantota</option>
    <option>Ambana</option>
    <option>Ambanpola</option>
    <option>Ambatalawa</option>
    <option>Ambatenna</option>
    <option>Ambepussa</option>
    <option>Ambewela</option>
    <option>Ambulugala</option>
    <option>Amitirigala</option>
    <option>Ampagala</option>
    <option>Ampara</option>
    <option>Ampegama</option>
    <option>Ampilanthurai</option>
    <option>Ampitiya</option>
    <option>Amugoda</option>
    <option>Amunumulla</option>
    <option>Anamaduwa</option>
    <option>Anangoda</option>
    <option>Andiambalama</option>
    <option>Andigama</option>
    <option>Andiyagala</option>
    <option>Angamuwa</option>
    <option>Angulugaha</option>
    <option>Angunakolapelessa</option>
    <option>Angunakolawewa</option>
    <option>Angunawila</option>
    <option>Anguruwatota</option>
    <option>Anhandiya</option>
    <option>Anhettigama</option>
    <option>Ankokkawala</option>
    <option>Ankumbura</option>
    <option>Anukkane</option>
    <option>Anuradhapura</option>
    <option>Aparekka</option>
    <option>Aragoda</option>
    <option>Araipattai</option>
    <option>Aralaganwila</option>
    <option>Aranayaka</option>
    <option>Arawakumbura</option>
    <option>Arawa</option>
    <option>Arawatta</option>
    <option>Aruggammana</option>
    <option>Aselapura</option>
    <option>Atabage</option>
    <option>Atakalanpanna</option>
    <option>Atakiriya</option>
    <option>Atale</option>
    <option>Ataragalla</option>
    <option>Ataragallewa</option>
    <option>Athuraliya</option>
    <option>Athurugiriya</option>
    <option>Attanagalla</option>
    <option>Attanakadawala</option>
    <option>Attawilluwa</option>
    <option>Avissawella</option>
    <option>Awukana</option>
    <option>Awulegama</option>
    <option>Ayagama</option>
    <option>Ayithiyamalai</option>
    <option>Ayiwela</option>
    <option>Badalgama</option>
    <option>Badalkumbura</option>
    <option>Baddegama</option>
    <option>Badulla</option>
    <option>Baduluoya</option>
    <option>Baduluwela</option>
    <option>Baduraliya</option>
    <option>Bakamuna</option>
    <option>Bakiella</option>
    <option>Bakinigahawela</option>
    <option>Bakmitiyawa</option>
    <option>Balaharuwa</option>
    <option>Balalla</option>
    <option>Balana</option>
    <option>Balangoda</option>
    <option>Balapitiya</option>
    <option>Ballaketuwa</option>
    <option>Bambaragahaela</option>
    <option>Bambaragaswewa</option>
    <option>Bambarapana</option>
    <option>Bamunukotuwa</option>
    <option>Banagala</option>
    <option>Bandagiriya Colony</option>
    <option>Bandaragama</option>
    <option>Bandara Koswatta</option>
    <option>Bandarawela</option>
    <option>Banduragoda</option>
    <option>Bangadeniya</option>
    <option>Baranankattuwa</option>
    <option>Barawakumbuka</option>
    <option>Barawardhana Oya</option>
    <option>Batagolladeniya</option>
    <option>Batapola</option>
    <option>Batatota</option>
    <option>Batawala</option>
    <option>Battaramulla</option>
    <option>Batticaloa</option>
    <option>Battuluoya</option>
    <option>Batugampola</option>
    <option>Batugoda</option>
    <option>Batumulla</option>
    <option>Batuwatta</option>
    <option>Batuwita</option>
    <option>Bawlana</option>
    <option>Beliatta</option>
    <option>Beligala(Sab)</option>
    <option>Beligamuwa</option>
    <option>Belihuloya</option>
    <option>Bellana</option>
    <option>Bemmulla</option>
    <option>Bengamuwa</option>
    <option>Bentota</option>
    <option>Beragama</option>
    <option>Beralapanathara</option>
    <option>Beralihela</option>
    <option>Beramada</option>
    <option>Berannawa</option>
    <option>Beruwala</option>
    <option>Bibilegama</option>
    <option>Bibile</option>
    <option>Bingiriya</option>
    <option>Biyagama IPZ</option>
    <option>Biyagama</option>
    <option>Bogahakumbura</option>
    <option>Bogahawewa</option>
    <option>Bogamulla</option>
    <option>Bogawantalawa</option>
    <option>Bokalagama</option>
    <option>Bollete (WP)</option>
    <option>Bolossagama</option>
    <option>Bolthumbe</option>
    <option>Bombuwala</option>
    <option>Bomluwageaina</option>
    <option>Boossa</option>
    <option>Bopagama</option>
    <option>Bopagoda</option>
    <option>Bopana</option>
    <option>Bopattalawa</option>
    <option>Bope</option>
    <option>Bopitiya</option>
    <option>Bopitiya (SAB)</option>
    <option>Boragas</option>
    <option>Boralanda</option>
    <option>Boralankada</option>
    <option>Boralesgamuwa</option>
    <option>Boralugoda</option>
    <option>Boraluwewa</option>
    <option>Bossella</option>
    <option>Bowalagama</option>
    <option>Bowela</option>
    <option>Boyagane</option>
    <option>Buckmigama</option>
    <option>Buddama</option>
    <option>Bujjampola</option>
    <option>Bujjomuwa</option>
    <option>Bulathkohupitiya</option>
    <option>Bulathsinhala</option>
    <option>Bulutota</option>
    <option>Buluwala</option>
    <option>Bundala</option>
    <option>Buthpitiya</option>
    <option>Buttala</option>
    <option>Central Camp</option>
    <option>Cheddipalayam</option>
    <option>Chenkaladi</option>
    <option>Chilaw</option>
    <option>China Bay</option>
    <option>Colombo 10</option>
    <option>Colombo 11</option>
    <option>Colombo 12</option>
    <option>Colombo 13</option>
    <option>Colombo 14</option>
    <option>Colombo 15</option>
    <option>Colombo 1</option>
    <option>Colombo 2</option>
    <option>Colombo 3</option>
    <option>Colombo 4</option>
    <option>Colombo 5</option>
    <option>Colombo 6</option>
    <option>Colombo 7</option>
    <option>Colombo 8</option>
    <option>Colombo 9</option>
    <option>Dadayamtalawa</option>
    <option>Dagampitiya</option>
    <option>Dagonna</option>
    <option>Dalukana</option>
    <option>Damana</option>
    <option>Damanewela</option>
    <option>Dambadeniya</option>
    <option>Dambagalla</option>
    <option>Dambana</option>
    <option>Dambulla</option>
    <option>Dambuluwana</option>
    <option>Damminna</option>
    <option>Dampahala</option>
    <option>Damunupola</option>
    <option>Danawala Thiniyawala</option>
    <option>Dankanda</option>
    <option>Dankotuwa</option>
    <option>Danowita</option>
    <option>Danture</option>
    <option>Daraluwa</option>
    <option>Daugala</option>
    <option>Dayagama Bazaar</option>
    <option>Debahera</option>
    <option>Debathgama</option>
    <option>Dedigamuwa</option>
    <option>Dedugala</option>
    <option>Dedunupitiya</option>
    <option>Deegala Lenama</option>
    <option>Deegalla</option>
    <option>Deegawapiya</option>
    <option>Deewala Pallegama</option>
    <option>Dehiattakandiya</option>
    <option>Dehiowita</option>
    <option>Dehiwala</option>
    <option>Dehiwatte</option>
    <option>Deiyandara</option>
    <option>Dekatana</option>
    <option>Dekinda</option>
    <option>Dela</option>
    <option>Deldeniya</option>
    <option>Delgoda</option>
    <option>Dellawa</option>
    <option>Delmella</option>
    <option>Deloluwa</option>
    <option>Deltara</option>
    <option>Deltota</option>
    <option>Delwagura</option>
    <option>Delwala</option>
    <option>Delwite</option>
    <option>Demalagama</option>
    <option>Demanhandiya</option>
    <option>Demataluwa</option>
    <option>Dematawewa</option>
    <option>Demodara</option>
    <option>Demuwatha</option>
    <option>Denagama</option>
    <option>Denipitiya</option>
    <option>Deniyaya</option>
    <option>Derangala</option>
    <option>Deraniyagala</option>
    <option>Devagiriya</option>
    <option>Devalahinda</option>
    <option>Devinuwara (Dondra)</option>
    <option>Dewagala</option>
    <option>Dewahuwa</option>
    <option>Dewalapola</option>
    <option>Dewalegama</option>
    <option>Dewanagala</option>
    <option>Dharga Town</option>
    <option>Diddeniya</option>
    <option>Digamadulla Weeragoda</option>
    <option>Diganatenna</option>
    <option>Digannewa</option>
    <option>Dikkapitiya</option>
    <option>Dikkumbura</option>
    <option>Dikoya</option>
    <option>Dikwella</option>
    <option>Dimbulagala</option>
    <option>Dimbulana</option>
    <option>Divulankadawala</option>
    <option>Divulapelessa</option>
    <option>Divulapitiya</option>
    <option>Divuldamana</option>
    <option>Divuldeniya</option>
    <option>Divullegoda</option>
    <option>Diwalakada</option>
    <option>Diyabeduma</option>
    <option>Diyagaha</option>
    <option>Diyakobala</option>
    <option>Diyalape</option>
    <option>Diyasenpura</option>
    <option>Diyatalawa</option>
    <option>Dodampe</option>
    <option>Dodanduwa</option>
    <option>Dodangaslanda</option>
    <option>Dodangoda</option>
    <option>Dolapihilla</option>
    <option>Dolosbage</option>
    <option>Doloswalakanda</option>
    <option>Doluwa</option>
    <option>Dombagahawela</option>
    <option>Dombagoda</option>
    <option>Dombemada</option>
    <option>Dompe</option>
    <option>Doragala</option>
    <option>Doragamuwa</option>
    <option>Dorakumbura</option>
    <option>Doratiyawa</option>
    <option>Dorawaka</option>
    <option>Dulgolla</option>
    <option>Dullewa</option>
    <option>Dumbara Manana</option>
    <option>Dummalasuriya</option>
    <option>Dunagaha</option>
    <option>Dunkannawa</option>
    <option>Dunkolawatta</option>
    <option>Dunukedeniya</option>
    <option>Dunumadalawa</option>
    <option>Dunumala</option>
    <option>Dunuwila</option>
    <option>Dunuwilapitiya</option>
    <option>Dutuwewa</option>
    <option>Echchilampattai</option>
    <option>Egodawela</option>
    <option>Eheliyagoda</option>
    <option>Ehetuwewa</option>
    <option>Ekala</option>
    <option>Ekamutugama</option>
    <option>Ekiriyankumbura</option>
    <option>Ekiriya</option>
    <option>Elahera</option>
    <option>Elamulla</option>
    <option>Elapatha</option>
    <option>Elayapattuwa</option>
    <option>Elibichchiya</option>
    <option>Elkaduwa</option>
    <option>Ellagala</option>
    <option>Ellagawa</option>
    <option>Ellakkala</option>
    <option>Ella</option>
    <option>Ella Tanabaddegama</option>
    <option>Ellaulla</option>
    <option>Ellawala</option>
    <option>Ellewewa</option>
    <option>Elpitiya</option>
    <option>Eluwankulama</option>
    <option>Embilipitiya</option>
    <option>Embogama</option>
    <option>Eppawala</option>
    <option>Eratna</option>
    <option>Eravur</option>
    <option>Erawula Junction</option>
    <option>Erepola</option>
    <option>Essella</option>
    <option>Etanawala</option>
    <option>Etawatunuwewa</option>
    <option>Etaweeragollewa</option>
    <option>Ethimalewewa</option>
    <option>Ethkandura</option>
    <option>Ettale</option>
    <option>Ettampitiya</option>
    <option>Ettiliwewa</option>
    <option>Etulgama</option>
    <option>Etungahakotuwa</option>
    <option>Gabbela</option>
    <option>Galabedda</option>
    <option>Galaboda</option>
    <option>Galadivulwewa</option>
    <option>Galagedara</option>
    <option>Galaha</option>
    <option>Galamuna</option>
    <option>Galapitagala</option>
    <option>Galapitamada</option>
    <option>Galatara</option>
    <option>Galauda</option>
    <option>Galedanda</option>
    <option>Galenbindunuwewa</option>
    <option>Galewela</option>
    <option>Galgamuwa</option>
    <option>Galhinna</option>
    <option>Galigamuwa Town</option>
    <option>Galkadawala</option>
    <option>Galkiriyagama</option>
    <option>Galkulama</option>
    <option>Gallellagama</option>
    <option>Gallella</option>
    <option>Galle</option>
    <option>Gallewa</option>
    <option>Galmetiyawa</option>
    <option>Galmuruwa</option>
    <option>Galnewa</option>
    <option>Galoya Junction</option>
    <option>Galpatha</option>
    <option>Galpatha(Sab)</option>
    <option>Galporuyaya</option>
    <option>Gamagoda</option>
    <option>Gambirigaswewa</option>
    <option>Gamewela</option>
    <option>Gammaduwa</option>
    <option>Gampaha</option>
    <option>Gampola</option>
    <option>Gandara</option>
    <option>Ganegoda</option>
    <option>Ganemulla</option>
    <option>Ganewalpola</option>
    <option>Gangala Puwakpitiya</option>
    <option>Gangeyaya</option>
    <option>Gangulandeniya</option>
    <option>Gantuna</option>
    <option>Gawaragiriya</option>
    <option>Gawarawela</option>
    <option>Gelioya</option>
    <option>Gemunupura</option>
    <option>Getahetta</option>
    <option>Getalawa</option>
    <option>Getamanna</option>
    <option>Gillimale</option>
    <option>Ginigathena</option>
    <option>Ginimellagaha</option>
    <option>Gintota</option>
    <option>Girandurukotte</option>
    <option>Girathalana</option>
    <option>Giritale</option>
    <option>Giriulla</option>
    <option>Gnanikulama</option>
    <option>Godagampola</option>
    <option>Godahena</option>
    <option>Godakawela</option>
    <option>Goda Koggalla</option>
    <option>Godamunna</option>
    <option>Godapitiya</option>
    <option>Godunna</option>
    <option>Gokaralla</option>
    <option>Gomagoda</option>
    <option>Gomarankadawala</option>
    <option>Gomilamawarala</option>
    <option>Gonagala</option>
    <option>Gonagalpura</option>
    <option>Gonagamuwa Uduwila</option>
    <option>Gonagantenna</option>
    <option>Gonagolla</option>
    <option>Gonahaddenawa</option>
    <option>Gonakele</option>
    <option>Gonamulla Junction</option>
    <option>Gonapinuwala</option>
    <option>Gonapola Junction</option>
    <option>Gonawala</option>
    <option>Gonawalapatana</option>
    <option>Gonawila</option>
    <option>Gonnoruwa</option>
    <option>Govinna</option>
    <option>Gunnepana</option>
    <option>Gurubewilagama</option>
    <option>Gurudeniya</option>
    <option>Gurulubadda</option>
    <option>Gurutalawa</option>
    <option>Habaraduwa</option>
    <option>Habarakada</option>
    <option>Habarana</option>
    <option>Haburugala</option>
    <option>Haggala</option>
    <option>Hakahinna</option>
    <option>Hakbellawaka</option>
    <option>Hakmana</option>
    <option>Hakuruwela</option>
    <option>Haldummulla</option>
    <option>Halgranoya</option>
    <option>Hali Ela</option>
    <option>Halkandawila</option>
    <option>Halloluwa</option>
    <option>Halmillawa Dambulla</option>
    <option>Halmillawetiya</option>
    <option>Halmillawewa</option>
    <option>Halpe</option>
    <option>Haltota</option>
    <option>Halvitigala Colony</option>
    <option>Halwala</option>
    <option>Halwatura</option>
    <option>Halwinna</option>
    <option>Hambantota</option>
    <option>Hambegamuwa</option>
    <option>Handaganawa</option>
    <option>Handagiriya</option>
    <option>Handapangoda</option>
    <option>Handawalapitiya</option>
    <option>Handessa</option>
    <option>Handugala</option>
    <option>Handungamuwa</option>
    <option>Hangarapitiya</option>
    <option>Hangunnawa</option>
    <option>Hanguranketha</option>
    <option>Hansayapalama</option>
    <option>Hanwella</option>
    <option>Hapugastalawa</option>
    <option>Hapugastenna</option>
    <option>Haputale</option>
    <option>Harangalagama</option>
    <option>Harankahawa</option>
    <option>Harasbedda</option>
    <option>Hasalaka</option>
    <option>Hatangala</option>
    <option>Hatarabage</option>
    <option>Hataraliyadda</option>
    <option>Hatton</option>
    <option>Hattota Amuna</option>
    <option>Hawpe</option>
    <option>Hebarawa</option>
    <option>Hedigalla Colony</option>
    <option>Hedunuwewa</option>
    <option>Heeloya</option>
    <option>Heiyanthuduwa</option>
    <option>Helahalpe</option>
    <option>Helamada</option>
    <option>Helapupula</option>
    <option>Hemmatagama</option>
    <option>Henegama</option>
    <option>Hengamuwa</option>
    <option>Hettimulla</option>
    <option>Hettipola</option>
    <option>Hewadiwela</option>
    <option>Hewaheta</option>
    <option>Hewainna</option>
    <option>Hewanakumbura</option>
    <option>Hidellana</option>
    <option>Hidogama</option>
    <option>Hikkaduwa</option>
    <option>Hilogama</option>
    <option>Hinatiyana Madawala</option>
    <option>Hindagala</option>
    <option>Hindagolla</option>
    <option>Hingula</option>
    <option>Hingurakdamana</option>
    <option>Hingurakgoda</option>
    <option>Hinguralakanda</option>
    <option>Hingurana</option>
    <option>Hingurukaduwa</option>
    <option>Hiniduma</option>
    <option>Hiramadagama</option>
    <option>Hiripitya</option>
    <option>Hiriwadunna</option>
    <option>Hiriyala Lenawa</option>
    <option>Hiruwalpola</option>
    <option>Hiswella</option>
    <option>Hitigegama</option>
    <option>Hiyare</option>
    <option>Hokandara</option>
    <option>Homagama</option>
    <option>Hondiyadeniya</option>
    <option>Hopton</option>
    <option>Horagala</option>
    <option>Horambawa</option>
    <option>Horampella</option>
    <option>Horana</option>
    <option>Horapawita</option>
    <option>Horawpatana</option>
    <option>Horewelagoda</option>
    <option>Horiwila</option>
    <option>Hulandawa</option>
    <option>Hulannuge</option>
    <option>Hulogedara</option>
    <option>Hulugalla</option>
    <option>Hungama</option>
    <option>Hunnasgiriya</option>
    <option>Hunumulla</option>
    <option>Hunupola</option>
    <option>Hurigaswewa</option>
    <option>Hurulunikawewa</option>
    <option>Idalgashinna</option>
    <option>Ihala Beligalla</option>
    <option>Ihalagama</option>
    <option>Ihala Gomugomuwa</option>
    <option>Ihala Katugampala</option>
    <option>Ihala Kottaramulla</option>
    <option>Ihala Madampella</option>
    <option>Ihala Puliyankulama</option>
    <option>Ihala Walpola</option>
    <option>Ilippadeniya</option>
    <option>Imbulana</option>
    <option>Imbulgasdeniya</option>
    <option>Imbulgoda</option>
    <option>Imbulgolla</option>
    <option>Imkkamam</option>
    <option>Inamaluwa</option>
    <option>Indulgodakanda</option>
    <option>Inginimitiya</option>
    <option>Inginiyagala</option>
    <option>Inguruwatta</option>
    <option>Ipologama</option>
    <option>Iriyagolla</option>
    <option>Ismailpuram</option>
    <option>Ithanawatta</option>
    <option>Ittademaliya</option>
    <option>Ittakanda</option>
    <option>Ittapana</option>
    <option>Ja-Ela</option>
    <option>Jaffna</option>
    <option>Jambugahapitiya</option>
    <option>Jangulla</option>
    <option>Jayanthipura</option>
    <option>Jayasiripura</option>
    <option>Julampitiya</option>
    <option>Kabagamuwa</option>
    <option>Kadawatha</option>
    <option>Kaddaiparichchan</option>
    <option>Kadigawa</option>
    <option>Kadugannawa</option>
    <option>Kaduwela</option>
    <option>Kagama</option>
    <option>Kahaduwa</option>
    <option>Kahandamodara</option>
    <option>Kahangama</option>
    <option>Kahapathwala</option>
    <option>Kahatagasdigiliya</option>
    <option>Kahatagollewa</option>
    <option>Kahataliyadda</option>
    <option>Kahataruppa</option>
    <option>Kahatowita</option>
    <option>Kahawala</option>
    <option>Kahawa</option>
    <option>Kahawatta</option>
    <option>Kaikawala</option>
    <option>Kakkapalliya</option>
    <option>Kalaganwatta</option>
    <option>Kalagedihena</option>
    <option>Kalakarambewa</option>
    <option>Kalankuttiya</option>
    <option>Kalaoya</option>
    <option>Kalatuwawa</option>
    <option>Kalawana</option>
    <option>Kalawedi Ulpotha</option>
    <option>Kalawila Kiranthidiya</option>
    <option>Kaleliya</option>
    <option>Kalingaela</option>
    <option>Kalkudah</option>
    <option>Kalladiya</option>
    <option>Kallanchiya</option>
    <option>Kallar</option>
    <option>Kalmunai</option>
    <option>Kalpitiya</option>
    <option>Kaltota</option>
    <option>Kaluaggala</option>
    <option>Kalubowitiyana</option>
    <option>Kalubululanda</option>
    <option>Kalugahakandura</option>
    <option>Kalugala</option>
    <option>Kalugamuwa</option>
    <option>Kalukele Badanagala</option>
    <option>Kalundawa</option>
    <option>Kalupahana</option>
    <option>Kalutara</option>
    <option>Kaluwanchikudi</option>
    <option>Kaluwankemy</option>
    <option>Kamburugamuwa</option>
    <option>Kamburupitiya</option>
    <option>Kanadeniyawala</option>
    <option>Kananke Bazaar</option>
    <option>Kananwila</option>
    <option>Kanattewewa</option>
    <option>Kandaketya</option>
    <option>Kandakuliya</option>
    <option>Kandalama</option>
    <option>Kandanagama</option>
    <option>Kandana</option>
    <option>Kandapola</option>
    <option>Kandaudapanguwa</option>
    <option>Kandavalai</option>
    <option>Kandawinna</option>
    <option>Kandegedara</option>
    <option>Kandepuhulpola</option>
    <option>Kandy</option>
    <option>Kannakipuram</option>
    <option>Kannankudah</option>
    <option>Kannattota</option>
    <option>Kanniya</option>
    <option>Kantalai</option>
    <option>Kantalai Sugar Factory</option>
    <option>Kapugallawa</option>
    <option>Kapugoda</option>
    <option>Kapuliyadde</option>
    <option>Karachchi</option>
    <option>Karadiyanaru</option>
    <option>Karagahagedara</option>
    <option>Karagahawewa</option>
    <option>Karagahinna</option>
    <option>Karagoda</option>
    <option>Karagoda Uyangoda</option>
    <option>Karambe</option>
    <option>Karandagolla</option>
    <option>Karandana</option>
    <option>Karandeniya</option>
    <option>Karangoda</option>
    <option>Karaputugala</option>
    <option>Karathivu</option>
    <option>Karativu</option>
    <option>Karatota</option>
    <option>Karawitagara</option>
    <option>Kariyamaditta</option>
    <option>Karuwalagaswewa</option>
    <option>Kashyapapura</option>
    <option>Katana</option>
    <option>Kataragama</option>
    <option>Kathiraveli</option>
    <option>Katiyawa</option>
    <option>Kattankudi</option>
    <option>Katudeniya</option>
    <option>Katugastota</option>
    <option>Katukitula</option>
    <option>Katunayake Air Force Camp</option>
    <option>Katunayake(FTZ)</option>
    <option>Katunayake</option>
    <option>Katuneriya</option>
    <option>Katupota</option>
    <option>Katuwana</option>
    <option>Katuwellegama</option>
    <option>Kavudupelella</option>
    <option>Kawantissapura</option>
    <option>Kawudulla</option>
    <option>Kawuduluwewa Stagell</option>
    <option>Kebillawela</option>
    <option>Kebithigollewa</option>
    <option>Keerthi Bandarapura</option>
    <option>Kegalle</option>
    <option>Kehelpannala</option>
    <option>Kehelwatta</option>
    <option>Kekanadurra</option>
    <option>Kekirawa</option>
    <option>Kekirihena</option>
    <option>Kekunagolla</option>
    <option>Kelanigama</option>
    <option>Kelaniya</option>
    <option>Kelinkanda</option>
    <option>Kella Junction</option>
    <option>Kendagolla</option>
    <option>Kendewa</option>
    <option>Kengalla</option>
    <option>Keppetipola</option>
    <option>Keppitiwalana</option>
    <option>Keselpotha</option>
    <option>Ketaboola</option>
    <option>Ketakumbura</option>
    <option>Ketawala Leula</option>
    <option>Ketawatta</option>
    <option>Kibissa</option>
    <option>Kilinochchi</option>
    <option>Kiliveddy</option>
    <option>Kimbulapitiya</option>
    <option>Kimbulwanaoya</option>
    <option>Kinniya</option>
    <option>Kiralogama</option>
    <option>Kirama</option>
    <option>Kirankulam</option>
    <option>Kiran</option>
    <option>Kiribathkumbura</option>
    <option>Kiriella</option>
    <option>Kirigalwewa</option>
    <option>Kiriibbanwewa</option>
    <option>Kirimetiyawa</option>
    <option>Kirimundalama</option>
    <option>Kirinda</option>
    <option>Kirindawa</option>
    <option>Kirindigalla</option>
    <option>Kirindiwela</option>
    <option>Kiriwanagama</option>
    <option>Kiriwattuduwa</option>
    <option>Kiriweldola</option>
    <option>Kiriwelkele</option>
    <option>Kitalawalana</option>
    <option>Kithalawa</option>
    <option>Kitulgala</option>
    <option>Kitulgoda</option>
    <option>Kitulhitiyawa</option>
    <option>Kitulwala</option>
    <option>Kiwula</option>
    <option>Kobeigane</option>
    <option>Kobonila</option>
    <option>Kochchikade</option>
    <option>Koddaikallar</option>
    <option>Kohilagedara</option>
    <option>Koholana</option>
    <option>Kokkaddichcholai</option>
    <option>Koknahara</option>
    <option>Kolabissa</option>
    <option>Kolamanthalawa</option>
    <option>Kolambageara</option>
    <option>Kolawenigama</option>
    <option>Kolombugama</option>
    <option>Kolongoda</option>
    <option>Kolonna</option>
    <option>Kolonnawa</option>
    <option>Komari</option>
    <option>Kondeniya</option>
    <option>Kongahawela</option>
    <option>Konwewa</option>
    <option>Kosdeniya</option>
    <option>Kosgama</option>
    <option>Kosgoda</option>
    <option>Kosgolla</option>
    <option>Koslanda</option>
    <option>Koswatta</option>
    <option>Kotadeniyawa</option>
    <option>Kotagala</option>
    <option>Kotagama</option>
    <option>Kotamuduna</option>
    <option>Kotapola</option>
    <option>Kotawehera Mankada</option>
    <option>Kotawehera</option>
    <option>Kotiyagala</option>
    <option>Kotiyakumbura</option>
    <option>Kotmale</option>
    <option>Kottantivu</option>
    <option>Kottapitiya</option>
    <option>Kottawagama</option>
    <option>Kottegoda</option>
    <option>Kottellena</option>
    <option>Kottukachchiya</option>
    <option>Kotugoda</option>
    <option>Kuchchaveli</option>
    <option>Kudagalgamuwa</option>
    <option>Kudakatnoruwa</option>
    <option>Kuda Uduwa</option>
    <option>Kudawa</option>
    <option>Kudawewa</option>
    <option>Kuleegoda</option>
    <option>Kuliyapitiya</option>
    <option>Kulugammana</option>
    <option>Kumaragama</option>
    <option>Kumarakattuwa</option>
    <option>Kumbalgamuwa</option>
    <option>Kumbaloluwa</option>
    <option>Kumbukgeta</option>
    <option>Kumbukkana</option>
    <option>Kumbukkandura</option>
    <option>Kumbukwela</option>
    <option>Kumbukwewa</option>
    <option>Kumburegama</option>
    <option>Kumburupiddy</option>
    <option>Kundasale</option>
    <option>Kuratihena</option>
    <option>Kurinchakemy</option>
    <option>Kurinjanpitiya</option>
    <option>Kuruketiyawa</option>
    <option>Kurukkalmadam</option>
    <option>Kurundankulama</option>
    <option>Kurunegala</option>
    <option>Kurupanawela</option>
    <option>Kuruwita</option>
    <option>Kuruwitenna</option>
    <option>Kuttiyagolla</option>
    <option>Labbala</option>
    <option>Labukele</option>
    <option>Labunoruwa</option>
    <option>Laggala Pallegama</option>
    <option>Lahugala</option>
    <option>Lakshauyana</option>
    <option>Landewela</option>
    <option>Lankagama</option>
    <option>Lankapatuna</option>
    <option>Laxapana</option>
    <option>lbbagamuwa</option>
    <option>Leemagahakotuwa</option>
    <option>Leliambe</option>
    <option>Lellopitiya</option>
    <option>Lenadora</option>
    <option>Lewangama</option>
    <option>lhala Halmillewa</option>
    <option>lhalahewessa</option>
    <option>lhala Kadigamuwa</option>
    <option>lhala Kobbekaduwa</option>
    <option>Lihiriyagama</option>
    <option>Lindula</option>
    <option>Liyangahawela</option>
    <option>lllagolla</option>
    <option>lllukkumbura</option>
    <option>llukhena</option>
    <option>lmaduwa</option>
    <option>lmbulpe</option>
    <option>lnduruwa</option>
    <option>lngiriya</option>
    <option>Loluwagoda</option>
    <option>Lonahettiya</option>
    <option>Lunama</option>
    <option>Lunugala</option>
    <option>Lunugama</option>
    <option>Lunugamwehera</option>
    <option>Lunuketiya Maditta</option>
    <option>Lunuwatta</option>
    <option>Lunuwila</option>
    <option>Mabodale</option>
    <option>Madahapola</option>
    <option>Madakumburumulla</option>
    <option>Madalagama</option>
    <option>Madampe</option>
    <option>Madapatha</option>
    <option>Madatugama</option>
    <option>Madawala Bazaar</option>
    <option>Madawalalanda</option>
    <option>Madawala Ulpotha</option>
    <option>Madelgamuwa</option>
    <option>Madipola</option>
    <option>Madugalla</option>
    <option>Madulkele</option>
    <option>Madulla</option>
    <option>Madulsima</option>
    <option>Maduragoda</option>
    <option>Madurankuliya</option>
    <option>Maduruoya</option>
    <option>Maeliya</option>
    <option>Magama</option>
    <option>Magedara</option>
    <option>Maggona</option>
    <option>Magulagama</option>
    <option>Maha Ambagaswewa</option>
    <option>Mahabage</option>
    <option>Mahabulankulama</option>
    <option>Mahadivulwewa</option>
    <option>Mahadoraliyadda</option>
    <option>Maha Elagamuwa</option>
    <option>Mahagalkadawala</option>
    <option>Mahagalwewa</option>
    <option>Mahagama Colony</option>
    <option>Mahagama</option>
    <option>Mahagirilla</option>
    <option>Mahailluppallama</option>
    <option>Mahakalupahana</option>
    <option>Mahakanadarawa</option>
    <option>Mahakumbukkadawala</option>
    <option>Mahamedagama</option>
    <option>Mahamukalanyaya</option>
    <option>Mahanagapura</option>
    <option>Mahananneriya</option>
    <option>Mahaoya</option>
    <option>Mahapallegama</option>
    <option>Mahapothana</option>
    <option>Maharachchimulla</option>
    <option>Maharagama</option>
    <option>Maharangalla</option>
    <option>Maharugiramam</option>
    <option>Mahasenpura</option>
    <option>Mahatalakolawewa</option>
    <option>Mahauswewa</option>
    <option>Mahawalatenna</option>
    <option>Mahawela</option>
    <option>Mahawela Sinhapura</option>
    <option>Mahawewa</option>
    <option>Mahawilachchiya</option>
    <option>Mahiyanganaya</option>
    <option>Maho</option>
    <option>Mailagaswewa</option>
    <option>Mailapitiya</option>
    <option>Makandura</option>
    <option>Makandura Sabara</option>
    <option>Makehelwala</option>
    <option>Makewita</option>
    <option>Makkanigama</option>
    <option>Makola</option>
    <option>Makuldeniya</option>
    <option>Makulella</option>
    <option>Makulewa</option>
    <option>Makulpotha</option>
    <option>Makulwewa</option>
    <option>Malabe</option>
    <option>Malagane</option>
    <option>Malalpola</option>
    <option>Maldeniya</option>
    <option>Malgalla Talangalla</option>
    <option>Malgoda</option>
    <option>Maliboda</option>
    <option>Maliduwa</option>
    <option>Maliyadda</option>
    <option>Mallikativu</option>
    <option>Malmaduwa</option>
    <option>Malwala Junction</option>
    <option>Malwanagama</option>
    <option>Malwana</option>
    <option>Malwatta</option>
    <option>Mamadala</option>
    <option>Mampitiya</option>
    <option>Mampuri</option>
    <option>Mananwatta</option>
    <option>Mandapola</option>
    <option>Mandaram Nuwara</option>
    <option>Mandawala</option>
    <option>Mandur</option>
    <option>Maneruwa</option>
    <option>Mangalaeliya</option>
    <option>Mangalagama</option>
    <option>Mankemi</option>
    <option>Mannar</option>
    <option>Mapakadawewa</option>
    <option>Mapakanda</option>
    <option>Mapalagama Central</option>
    <option>Mapalagama</option>
    <option>Maradankadawala</option>
    <option>Maradankalla</option>
    <option>Maraka</option>
    <option>Maramba</option>
    <option>Marandagahamula</option>
    <option>Marapana</option>
    <option>Marassana</option>
    <option>Marathamune</option>
    <option>Marawa</option>
    <option>Marawila</option>
    <option>Mariarawa</option>
    <option>Marymount Colony</option>
    <option>Maskeliya</option>
    <option>Maspanna</option>
    <option>Maspotha</option>
    <option>Maswela</option>
    <option>Matale</option>
    <option>Matara</option>
    <option>Mattaka</option>
    <option>Matugama</option>
    <option>Maturata</option>
    <option>Matuwagalagama</option>
    <option>Maussagolla</option>
    <option>Mawadichenai</option>
    <option>Mawanagama</option>
    <option>Mawanella</option>
    <option>Mawathagama</option>
    <option>Mawatura</option>
    <option>Medagalatur</option>
    <option>Medagana</option>
    <option>Meda-Keembiya</option>
    <option>Medamahanuwara</option>
    <option>Medamulana</option>
    <option>Medawachchiya</option>
    <option>Medawala Harispattuwa</option>
    <option>Medawelagama</option>
    <option>Medawela Udukinda</option>
    <option>Meddekanda</option>
    <option>Medirigiriya</option>
    <option>Mediripitiya</option>
    <option>Medivawa</option>
    <option>Meegahakiula</option>
    <option>Meegahatenna</option>
    <option>Meegalawa</option>
    <option>Meegama</option>
    <option>Meegaswewa</option>
    <option>Meegoda</option>
    <option>Meetalawa</option>
    <option>Meetanwala</option>
    <option>Meetiyagoda</option>
    <option>Meewellawa</option>
    <option>Megoda Kalugamuwa</option>
    <option>Megodawewa</option>
    <option>Melipitiya</option>
    <option>Mellawagedara</option>
    <option>Melsiripura</option>
    <option>Menikdiwela</option>
    <option>Menikhinna</option>
    <option>Metigahatenna</option>
    <option>Metihakka</option>
    <option>Metikumbura</option>
    <option>Metiyagane</option>
    <option>Middeniya</option>
    <option>Miella</option>
    <option>Migahajandur</option>
    <option>Migastenna Sabara</option>
    <option>Mihintale</option>
    <option>Millaniya</option>
    <option>Millawana</option>
    <option>Millewa</option>
    <option>Mimure</option>
    <option>Minhettiya</option>
    <option>Minigamuwa</option>
    <option>Minipe</option>
    <option>Minipura Dumbara</option>
    <option>Minneriya</option>
    <option>Minuwangete</option>
    <option>Minuwangoda</option>
    <option>Mipanawa</option>
    <option>Mipilimana</option>
    <option>Mirahawatta</option>
    <option>Miravodai</option>
    <option>Mirigama</option>
    <option>Mirihanagama</option>
    <option>Mirissa</option>
    <option>Miriswatta</option>
    <option>Miriyabedda</option>
    <option>Mithirigala</option>
    <option>Mitipola</option>
    <option>Miwanapalana</option>
    <option>Miyanakandura</option>
    <option>Miyanawita</option>
    <option>Modarawana</option>
    <option>Molagoda</option>
    <option>Molkawa</option>
    <option>Monaragala</option>
    <option>Monnekulama</option>
    <option>Moragahapallama</option>
    <option>Moragala Kirillapone</option>
    <option>Moragane</option>
    <option>Moragollagama</option>
    <option>Morahela</option>
    <option>Morahenagama</option>
    <option>Morakewa</option>
    <option>Morapitiya</option>
    <option>Morathiha</option>
    <option>Moratuwa</option>
    <option>Morawaka</option>
    <option>Moretuwegama</option>
    <option>Morontota</option>
    <option>Morontuduwa</option>
    <option>Mount Lavinia</option>
    <option>Mudalakkuliya</option>
    <option>Muddaragama</option>
    <option>Mudungoda</option>
    <option>Mugunuwatawana</option>
    <option>Mukkutoduwawa</option>
    <option>Mulatiyana Junction</option>
    <option>Mulendiyawala</option>
    <option>Mulgama</option>
    <option>Mulkirigala</option>
    <option>Mulkiriyawa</option>
    <option>Mullativu</option>
    <option>Mullegama</option>
    <option>Mulleriyawa New Town</option>
    <option>Mullipothana</option>
    <option>Munamaldeniya</option>
    <option>Mundel</option>
    <option>Munwatta</option>
    <option>Murakottanchanai</option>
    <option>Muriyakadawala</option>
    <option>Murutalawa</option>
    <option>Muruthagahamulla</option>
    <option>Muruthenge</option>
    <option>Muttibendiwila</option>
    <option>Mutugala</option>
    <option>Mutur</option>
    <option>Muwandeniya</option>
    <option>Nabadewa</option>
    <option>Nachchaduwa</option>
    <option>Nadugala</option>
    <option>Nagoda</option>
    <option>Nagollagama</option>
    <option>Nagollagoda</option>
    <option>Naimana</option>
    <option>Nainamadama</option>
    <option>Nakiyadeniya</option>
    <option>Nakkala</option>
    <option>Nakkawatta</option>
    <option>Nakulugamuwa</option>
    <option>Nalanda</option>
    <option>Nalladarankattuwa</option>
    <option>Namaloya</option>
    <option>Namalpura</option>
    <option>Namunukula</option>
    <option>Nannapurawa</option>
    <option>Nanuoya</option>
    <option>Napawela</option>
    <option>Narammala</option>
    <option>Narangala</option>
    <option>Narangoda</option>
    <option>Naranpanawa</option>
    <option>Naranwala</option>
    <option>Narawelpita</option>
    <option>Nattandiya</option>
    <option>Nattarampotha</option>
    <option>Naula</option>
    <option>Navagirinagar</option>
    <option>Navatkadu</option>
    <option>Navithanveli</option>
    <option>Nawadagala</option>
    <option>Nawagattegama</option>
    <option>Nawalakanda</option>
    <option>Nawalapitiya</option>
    <option>Nawamedagama</option>
    <option>Nawana</option>
    <option>Nawasenapura</option>
    <option>Nawatalwatta</option>
    <option>Nawathispane</option>
    <option>Nawattuduwa</option>
    <option>NawinnaPinnakanda</option>
    <option>Nayapana Janapadaya</option>
    <option>Neboda</option>
    <option>Nedungamuwa</option>
    <option>Neelapola</option>
    <option>Negampaha</option>
    <option>Negombo</option>
    <option>Nelliyadda</option>
    <option>Nelliya</option>
    <option>Nelumgama</option>
    <option>Nelumwewa</option>
    <option>Nelundeniya</option>
    <option>Neluwa</option>
    <option>Netolpitiya</option>
    <option>Nihiluwa</option>
    <option>Nikadalupotha</option>
    <option>Nikahetikanda</option>
    <option>Nikapotha</option>
    <option>Nikaweratiya</option>
    <option>Nilaveli</option>
    <option>Nildandahinna</option>
    <option>Nilgala</option>
    <option>Nillambe</option>
    <option>Nindana</option>
    <option>Nintavur</option>
    <option>Niralagama</option>
    <option>Nissanka Uyana</option>
    <option>Nittambuwa</option>
    <option>Nivitigala</option>
    <option>Niwandama</option>
    <option>Niyadurupola</option>
    <option>Nochchiyagama</option>
    <option>Noori</option>
    <option>Norachcholai</option>
    <option>Norwood</option>
    <option>Nugagolla</option>
    <option>Nugaliyadda</option>
    <option>Nugatalawa</option>
    <option>Nugawela</option>
    <option>Nugegoda</option>
    <option>Nuwara Eliya</option>
    <option>Nuwaragala</option>
    <option>Obbegoda</option>
    <option>Oddamavadi</option>
    <option>Ohiya</option>
    <option>Okkampitiya</option>
    <option>Oluvil</option>
    <option>Omalpe</option>
    <option>Onegama</option>
    <option>Opalgala</option>
    <option>Opanayaka</option>
    <option>Opatha</option>
    <option>Orubendi Siyambalawa</option>
    <option>Ovilikanda</option>
    <option>Pachchilaipalli</option>
    <option>Padagoda</option>
    <option>Padalangala</option>
    <option>Padavi Maithripura</option>
    <option>Padavi Parakramapura</option>
    <option>Padavi Sripura</option>
    <option>Padavi Sritissapura</option>
    <option>Padaviya</option>
    <option>Padawkema</option>
    <option>Padeniya</option>
    <option>Padikaramaduwa</option>
    <option>Padiwela</option>
    <option>Padiyapelella</option>
    <option>Padiyatalawa</option>
    <option>Padukka</option>
    <option>Pahala Andarawewa</option>
    <option>Pahalagama</option>
    <option>Pahalagiribawa</option>
    <option>Pahala Halmillewa</option>
    <option>Pahalahewessa</option>
    <option>Pahalalanda</option>
    <option>Pahala Maragahawe</option>
    <option>Pahala Millawa</option>
    <option>Pahalarathkinda</option>
    <option>Pahamune</option>
    <option>Paiyagala</option>
    <option>Palagala</option>
    <option>Palamunai</option>
    <option>Palapathwela</option>
    <option>Palatuwa</option>
    <option>Palaviya</option>
    <option>Pallama</option>
    <option>Pallebedda</option>
    <option>Pallebowala</option>
    <option>Pallekanda</option>
    <option>Pallekiruwa</option>
    <option>Pallekotuwa</option>
    <option>Pallepola</option>
    <option>Pallewela</option>
    <option>Palliwasalturai</option>
    <option>Palugasdamana</option>
    <option>Palugaswewa</option>
    <option>Palukadawala</option>
    <option>Pambagolla</option>
    <option>Pamunugama</option>
    <option>Pamunuwatta</option>
    <option>Panadaragama</option>
    <option>Panadura</option>
    <option>Panagamuwa</option>
    <option>Panaliya</option>
    <option>Panama</option>
    <option>Panamura</option>
    <option>Panangala</option>
    <option>Panapitiya</option>
    <option>Panapola</option>
    <option>Panawala</option>
    <option>Pandukabayapura</option>
    <option>Pandulagama</option>
    <option>Pangura</option>
    <option>Panichankemi</option>
    <option>Panirendawa</option>
    <option>Pankudavely</option>
    <option>Pankulam</option>
    <option>Panliyadda</option>
    <option>Pannalagama</option>
    <option>Pannala</option>
    <option>Pannila</option>
    <option>Pannimulla Panagoda</option>
    <option>Pannipitiya</option>
    <option>Pansiyagama</option>
    <option>Panvila</option>
    <option>Panwilatenna</option>
    <option>Paradeka</option>
    <option>Paragahakele</option>
    <option>Paragala</option>
    <option>Paragastota</option>
    <option>Paragoda</option>
    <option>Paraigama</option>
    <option>Parakaduwa</option>
    <option>Parakramasamudraya</option>
    <option>Parakumpura</option>
    <option>Parana ThanaYamgoda</option>
    <option>Parangiyawadiya</option>
    <option>Parapamulla</option>
    <option>Parape</option>
    <option>Parasangahawewa</option>
    <option>Pasbage</option>
    <option>Pasgoda</option>
    <option>Passara</option>
    <option>Pasyala</option>
    <option>Patana</option>
    <option>Pathanewatta</option>
    <option>Pattampitiya</option>
    <option>Pattitalawa</option>
    <option>Pattiyagedara</option>
    <option>Pattiya Watta</option>
    <option>Pebotuwa</option>
    <option>Pelagahatenna</option>
    <option>Pelanda</option>
    <option>Pelatiyawa</option>
    <option>Pelawatta</option>
    <option>Peliyagoda</option>
    <option>Pelmadulla</option>
    <option>Pemaduwa</option>
    <option>Penetiyana</option>
    <option>Pepiliyawala</option>
    <option>Peradeniya</option>
    <option>Perakanatta</option>
    <option>Perawella</option>
    <option>Perimiyankulama</option>
    <option>Periyakadneluwa</option>
    <option>Periyaneelavanai</option>
    <option>Periyaporativu</option>
    <option>Periyapullumalai</option>
    <option>Pethiyagoda</option>
    <option>Pihimbiyagolewa</option>
    <option>Pihimbiya Ratmale</option>
    <option>Pihimbuwa</option>
    <option>Pilawala</option>
    <option>Pilessa</option>
    <option>Pilimatalawa</option>
    <option>Piliyandala</option>
    <option>Pillaiyaradi</option>
    <option>Pimbura</option>
    <option>Pimburattewa</option>
    <option>Pinnawala</option>
    <option>Pitabeddara</option>
    <option>Pitagaldeniya</option>
    <option>Pitakumbura</option>
    <option>Pitamaruwa</option>
    <option>Pitapola</option>
    <option>Pitawala</option>
    <option>Pitigala</option>
    <option>Pitipana Homagama</option>
    <option>Poddala</option>
    <option>Poholiyadda</option>
    <option>Pokunuwita</option>
    <option>Polgahawela</option>
    <option>Polgampola</option>
    <option>Polgasowita</option>
    <option>Polgolla</option>
    <option>Polonnaruwa</option>
    <option>Polpithimukulana</option>
    <option>Polpitigama</option>
    <option>Polwaga Janapadaya</option>
    <option>Poonakary</option>
    <option>Porawagama</option>
    <option>Poruwedanda</option>
    <option>Pothdeniya</option>
    <option>Pothuhera</option>
    <option>Pothukoladeniya</option>
    <option>Pothupitiya</option>
    <option>Pothuwatawana</option>
    <option>Pottuvil</option>
    <option>Pubbiliya</option>
    <option>Pubbogama</option>
    <option>Pugoda</option>
    <option>Puhulpola</option>
    <option>Puhulwella</option>
    <option>Pujapitiya</option>
    <option>Pulastigama</option>
    <option>Pulmoddai</option>
    <option>Punanai</option>
    <option>Pundaluoya</option>
    <option>Punewa</option>
    <option>Pupuressa</option>
    <option>Pussellawa</option>
    <option>Puswelitenna</option>
    <option>Puthukudiyiruppu</option>
    <option>Puttalam Cement Factory</option>
    <option>Puttalam</option>
    <option>Putuhapuwa</option>
    <option>Puwakpitiya</option>
    <option>Radawadunna</option>
    <option>Radawana</option>
    <option>Radawela</option>
    <option>Raddolugama</option>
    <option>Ragama</option>
    <option>Rajagalatenna</option>
    <option>Rajakadaluwa</option>
    <option>Rajanganaya</option>
    <option>Rajawaka</option>
    <option>Rajawella</option>
    <option>Rakwana</option>
    <option>Rambewa</option>
    <option>Ramboda</option>
    <option>Rambukkana</option>
    <option>Rambukpitiya</option>
    <option>Rambukwella</option>
    <option>Rammalawarapitiya</option>
    <option>Rampathwila</option>
    <option>Ranakeliya</option>
    <option>Ranala</option>
    <option>Ranamuregama</option>
    <option>Randeniya</option>
    <option>Rangala</option>
    <option>Ranmuduwewa</option>
    <option>Ranna</option>
    <option>Ranorawa</option>
    <option>Ransegoda</option>
    <option>Rantembe</option>
    <option>Rantotuwila</option>
    <option>Ranwala</option>
    <option>Rassagala</option>
    <option>Ratgama</option>
    <option>Rathmalgahawewa</option>
    <option>Rathukohodigala</option>
    <option>Ratkarawwa</option>
    <option>Ratmale</option>
    <option>Ratmalwala</option>
    <option>Ratna Hangamuwa</option>
    <option>Ratnapura</option>
    <option>Rattota</option>
    <option>Remunagoda</option>
    <option>Ridibendiella</option>
    <option>Ridigama</option>
    <option>Ridimaliyadda</option>
    <option>Rikillagaskada</option>
    <option>Rilpola</option>
    <option>Rottawewa</option>
    <option>Rotumba</option>
    <option>Rozella</option>
    <option>Ruggahawila</option>
    <option>Rukmale</option>
    <option>Rupaha</option>
    <option>RU/Ridiyagama</option>
    <option>Ruwalwela</option>
    <option>Ruwaneliya</option>
    <option>Ruwanwella</option>
    <option>Sainthamaruthu</option>
    <option>Saliya Asokapura</option>
    <option>Saliyapura</option>
    <option>Saliyawewa Junction</option>
    <option>Samanalawewa</option>
    <option>Samanthurai</option>
    <option>Sampaltivu</option>
    <option>Sampoor</option>
    <option>Sandalankawa</option>
    <option>Sangarajapura</option>
    <option>Santhipura</option>
    <option>Seaforth Colony</option>
    <option>Seeduwa</option>
    <option>Seeppukulama</option>
    <option>Selagama</option>
    <option>Sella Kataragama</option>
    <option>Senapura</option>
    <option>Senarathwela</option>
    <option>Serankada</option>
    <option>Serukele</option>
    <option>Serunuwara</option>
    <option>Seruwila</option>
    <option>Sevanapitiya</option>
    <option>Sewanagala</option>
    <option>Siddamulla</option>
    <option>Sigiriya</option>
    <option>Silmiyapura</option>
    <option>Sinhagama</option>
    <option>Sirajnagar</option>
    <option>Sirambiadiya</option>
    <option>Sirimalgoda</option>
    <option>Siripura</option>
    <option>Sirisetagama</option>
    <option>Sivalakulama</option>
    <option>Siyambalagashene</option>
    <option>Siyambalagoda</option>
    <option>Siyambalagune</option>
    <option>Siyambalanduwa</option>
    <option>Siyambalangamuwa</option>
    <option>Siyambalape</option>
    <option>Siyambalawewa</option>
    <option>Siyambalewa</option>
    <option>Solepura</option>
    <option>Solewewa</option>
    <option>Somapura</option>
    <option>Sooriyawewa Town</option>
    <option>Sorabora Colony</option>
    <option>Soragune</option>
    <option>Soranatota</option>
    <option>Spring Valley</option>
    <option>Sravasthipura</option>
    <option>Sri Jayawardenepu</option>
    <option>Sri Palabaddala</option>
    <option>Sudagala</option>
    <option>Sultanagoda</option>
    <option>Sunandapura</option>
    <option>Sungavila</option>
    <option>Suriara</option>
    <option>Tabbowa</option>
    <option>Talagampola</option>
    <option>Talagoda Junction</option>
    <option>Talahena</option>
    <option>Talakiriyagama</option>
    <option>Talakolahinna</option>
    <option>Talatuoya</option>
    <option>Talawakele</option>
    <option>Talawa</option>
    <option>Talawattegedara</option>
    <option>Talawatugoda</option>
    <option>Talawila Church</option>
    <option>Taldena</option>
    <option>Talgaspe</option>
    <option>Talgaspitiya</option>
    <option>Talgaswela</option>
    <option>Talpe</option>
    <option>Talpotha</option>
    <option>Tamankaduwa</option>
    <option>Tambala</option>
    <option>Tambutta</option>
    <option>Tambuttegama</option>
    <option>Tammennawa</option>
    <option>Tampalakamam</option>
    <option>Tanamalwila</option>
    <option>Tangalla</option>
    <option>Tanjantenna</option>
    <option>Tantirimale</option>
    <option>Tawalama</option>
    <option>Tawalantenna</option>
    <option>Tebuwana</option>
    <option>Teldeniya</option>
    <option>Telhiriyawa</option>
    <option>Teligama</option>
    <option>Telijjawila</option>
    <option>Tempitiya</option>
    <option>Tennekumbura</option>
    <option>Tennepanguwa</option>
    <option>Teppanawa</option>
    <option>Teripeha</option>
    <option>Thalahitimulla</option>
    <option>Thalakolawewa</option>
    <option>Thalwita</option>
    <option>Thambagalla</option>
    <option>Thambiluvil</option>
    <option>Thannamunai</option>
    <option>Tharana Udawela</option>
    <option>Thettativu</option>
    <option>Thihagoda</option>
    <option>Thikkodai</option>
    <option>Thimbirigaskatuwa</option>
    <option>Thimbiriyawa</option>
    <option>Thirupalugamam</option>
    <option>Tholangamuwa</option>
    <option>Thotawella</option>
    <option>Thuraineelavanai</option>
    <option>Timbirigaspitiya</option>
    <option>Tiranagama</option>
    <option>Tirappane</option>
    <option>Tiriyayi</option>
    <option>Tirukovil</option>
    <option>Tisogama</option>
    <option>Tissamaharama</option>
    <option>Tittagonewa</option>
    <option>Tittapattara</option>
    <option>Toduwawa</option>
    <option>Toppur</option>
    <option>Torayaya</option>
    <option>Trincomalee</option>
    <option>Tulhiriya</option>
    <option>Tummodara</option>
    <option>Tunkama</option>
    <option>Tuntota</option>
    <option>Tuttiripitigama</option>
    <option>Udagaldeniya</option>
    <option>Uda Gomadiya</option>
    <option>Udaha Hawupe</option>
    <option>Udahentenna</option>
    <option>Udahingulwala</option>
    <option>Udakarawita</option>
    <option>Udalamatta</option>
    <option>Udamadura</option>
    <option>Udamattala</option>
    <option>Udaniriella</option>
    <option>Uda Peradeniya</option>
    <option>Udapotha</option>
    <option>Udappuwa</option>
    <option>Udapussallawa</option>
    <option>Udasgiriya</option>
    <option>Udatalawinna</option>
    <option>Udatenna</option>
    <option>Udathuthiripitiya</option>
    <option>Udawalawe</option>
    <option>Udawatta</option>
    <option>Udispattuwa</option>
    <option>Udubaddawa</option>
    <option>Ududumbara</option>
    <option>Udugama</option>
    <option>Udugampola</option>
    <option>Uduhawara</option>
    <option>Udumulla</option>
    <option>Udunuwara Colony</option>
    <option>Uduwahinna</option>
    <option>Uduwa</option>
    <option>Uduwara</option>
    <option>Uduwela</option>
    <option>Uggalboda</option>
    <option>Uhana</option>
    <option>Uhumiya</option>
    <option>Ukuwela</option>
    <option>Ulapane</option>
    <option>Ullinduwawa</option>
    <option>Ulpothagama</option>
    <option>Ulpotha Pallekele</option>
    <option>Uluvitike</option>
    <option>Unagalavehera</option>
    <option>Unawatuna</option>
    <option>Undugoda</option>
    <option>Unenwitiya</option>
    <option>Unnichchai</option>
    <option>Unuwinna</option>
    <option>Upuldeniya</option>
    <option>Uragaha</option>
    <option>Uragasmanhandiya</option>
    <option>Uraniya</option>
    <option>Urapola</option>
    <option>Uridyawa</option>
    <option>Urubokka</option>
    <option>Urugamuwa</option>
    <option>Urumutta</option>
    <option>Usgala Siyabmalangamuwa</option>
    <option>Ussapitiya</option>
    <option>Uswetakeiyawa</option>
    <option>Uswewa</option>
    <option>Uttimaduwa</option>
    <option>Utumgama</option>
    <option>Uva Deegalla</option>
    <option>Uva Gangodagama</option>
    <option>Uva Karandagolla</option>
    <option>Uva Kudaoya</option>
    <option>Uva Mawelagama</option>
    <option>Uvaparanagama</option>
    <option>Uva Pelwatta</option>
    <option>Uva Tenna</option>
    <option>Uva Tissapura</option>
    <option>Uva Uduwara</option>
    <option>Vakaneri</option>
    <option>Vakarai</option>
    <option>Valaichenai</option>
    <option>Vanathawilluwa</option>
    <option>Vantharumoolai</option>
    <option>Vavuniya</option>
    <option>Veddagala</option>
    <option>Velamboda</option>
    <option>Vellamanal</option>
    <option>Vellavely</option>
    <option>Veyangalla</option>
    <option>Veyangoda</option>
    <option>Viharahena</option>
    <option>Viharapalugama</option>
    <option>Vijeriya</option>
    <option>Vijithapura</option>
    <option>Vitharandeniya</option>
    <option>Wadakada</option>
    <option>Wadduwa</option>
    <option>Wadinagala</option>
    <option>Wadumunnegedara</option>
    <option>Waga</option>
    <option>Wahacotte</option>
    <option>Wahakula</option>
    <option>Wahalkada</option>
    <option>Wahamalgollewa</option>
    <option>Waharaka</option>
    <option>Waikkal</option>
    <option>Wakwella</option>
    <option>Walagambahuwa</option>
    <option>Walagedara</option>
    <option>Walahanduwa</option>
    <option>Walahaviddawewa</option>
    <option>Walakanda</option>
    <option>Walakumburumulla</option>
    <option>Walallawita</option>
    <option>Walapane</option>
    <option>Walasgala</option>
    <option>Walasmulla</option>
    <option>Walawela</option>
    <option>Waleboda</option>
    <option>Walgammulla</option>
    <option>Walpita</option>
    <option>Walpola (WP)</option>
    <option>Wanagamuwa</option>
    <option>Wanaluwewa</option>
    <option>Wanchawela</option>
    <option>Wanduramba</option>
    <option>Wanela</option>
    <option>Wannigama</option>
    <option>Wannikudawewa</option>
    <option>Wannilhalagama</option>
    <option>Wannirasnayakapura</option>
    <option>Warakapola</option>
    <option>Waralla</option>
    <option>Warawewa</option>
    <option>Wariyapola</option>
    <option>Warukandeniya</option>
    <option>Warunagama</option>
    <option>Waskaduwa</option>
    <option>Watagoda Harispattuwa</option>
    <option>Watagoda</option>
    <option>Watapotha</option>
    <option>Watareka</option>
    <option>Watawala</option>
    <option>Wathurugama</option>
    <option>Watinapaha</option>
    <option>Wattala</option>
    <option>Wattappola</option>
    <option>Wattegama</option>
    <option>Watugahamulla</option>
    <option>Watugedara</option>
    <option>Watura</option>
    <option>Waturawa</option>
    <option>Watuwatta</option>
    <option>Weboda</option>
    <option>Wedikumbura</option>
    <option>Weeoya</option>
    <option>Weeraketiya</option>
    <option>Weerapokuna</option>
    <option>Weerawila NewTown</option>
    <option>Weerawila</option>
    <option>Wegalla</option>
    <option>Wegowwa</option>
    <option>Weherayaya Handapanagala</option>
    <option>Wehigala</option>
    <option>Weihena</option>
    <option>Wekandawela</option>
    <option>Welangahawatte</option>
    <option>Welawa Juncton</option>
    <option>Weligalla</option>
    <option>Weligama</option>
    <option>Weligampola</option>
    <option>Weligatta</option>
    <option>Weligepola</option>
    <option>Welihelatenna</option>
    <option>Welikanda</option>
    <option>Welimada</option>
    <option>Welimuwapotana</option>
    <option>Welioya Project</option>
    <option>Welipathayaya</option>
    <option>Welipennagahamulla</option>
    <option>Welipenna</option>
    <option>Weliveriya</option>
    <option>Wellagala</option>
    <option>Wellarawa</option>
    <option>Wellawa</option>
    <option>Wellawaya</option>
    <option>Welmilla Junction</option>
    <option>Welpalla</option>
    <option>Wendaruwa</option>
    <option>Wennappuwa</option>
    <option>Wennoruwa</option>
    <option>Weragala</option>
    <option>Weragantota</option>
    <option>Werapitya</option>
    <option>Werellagama</option>
    <option>Werunketagoda</option>
    <option>Wettawa</option>
    <option>Weuda</option>
    <option>Wewagama</option>
    <option>Wewalawewa</option>
    <option>Wewatta</option>
    <option>Weweldeniya</option>
    <option>Wewelwatta</option>
    <option>Widulipura</option>
    <option>Wijayabapura</option>
    <option>Wijebahukanda</option>
    <option>Wijeyakatupotha</option>
    <option>Wikiliya</option>
    <option>Wilanagama</option>
    <option>Wilaoya</option>
    <option>Wilgamuwa</option>
    <option>Wilpita</option>
    <option>Wilpotha</option>
    <option>Wineethagama</option>
    <option>Yagirala</option>
    <option>Yahalatenna</option>
    <option>Yakkalamulla</option>
    <option>Yakkala</option>
    <option>Yakwila</option>
    <option>Yalagamuwa</option>
    <option>Yalwela</option>
    <option>Yatadolawatta</option>
    <option>Yatagama</option>
    <option>Yatalamatta</option>
    <option>Yatapana</option>
    <option>Yatawara Junction</option>
    <option>Yatawatta</option>
    <option>Yatigala</option>
    <option>Yatigaloluwa</option>
    <option>Yatihalagala</option>
    <option>Yatiyana</option>
    <option>Yatiyantota</option>
    <option>Yattogoda</option>
    <option>Yodaela</option>
    <option>Yogiyana</option>
    <option>Yudaganawa</option>
</datalist>
